# tpda3
# Toolbar interface configuration
# Here ca be added new toolbar buttons
# The toolbar Id's start at 2000 and the name with tb2
---
toolbar2:
  tb2ad:
    id:      2001
    type:    _item_normal
    icon:    actitemadd16
    tooltip: Add new row
    help:    Add new row in table
    sep:     none
    state:
      rec:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
      det:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
  tb2rm:
    id      : 2002
    type    : _item_normal
    icon    : actitemdelete16
    tooltip : Remove row
    help    : Remove row from table
    sep     : none
    state:
      rec:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
      det:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
  tb2rr:
    id      : 2003
    type    : _item_normal
    icon    : actreload16
    tooltip : Remove row
    help    : Remove row from table
    sep     : none
    state:
      rec:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
      det:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
  tb2sv:
    id      : 2004
    type    : _item_normal
    icon    : filesave16
    tooltip : Remove row
    help    : Remove row from table
    sep     : none
    state:
      rec:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
      det:
        idle: disabled
        add : normal
        edit: normal
        find: disabled
        sele: disabled
